<?php

declare(strict_types=1);

use BlockBuilder\Tests\Integration\Support\DisposableEnvironmentGuard;
use Concrete\Core\Block\Block;
use Concrete\Core\Block\BlockType\BlockType;
use Concrete\Core\Database\Connection\Connection;
use Concrete\Core\Entity\Block\BlockType\BlockType as BlockTypeEntity;
use Concrete\Core\Entity\Package as PackageEntity;
use Concrete\Core\Foundation\ClassAutoloader;
use Concrete\Core\Package\PackageService;
use Concrete\Core\User\User;

require_once __DIR__ . DIRECTORY_SEPARATOR . 'Support' . DIRECTORY_SEPARATOR . 'DisposableEnvironmentGuard.php';

const LEGACY_FIXTURE_HANDLE = 'block_builder_integration_upgrade_fixture';
const LEGACY_FIXTURE_MAIN_TABLE = 'btBlockBuilderIntegrationUpgradeFixture';
const LEGACY_FIXTURE_ENTRIES_TABLE = 'btBlockBuilderIntegrationUpgradeFixtureEntries';

if (count($argv) !== 1) {
    fwrite(STDERR, "Usage: php create-legacy-upgrade-fixture.php\n");
    exit(2);
}

$configuredPublicRoot = getenv('BLOCK_BUILDER_INTEGRATION_PUBLIC_ROOT');
if (!is_string($configuredPublicRoot) || $configuredPublicRoot === '') {
    throw new RuntimeException('The disposable public root is missing.');
}
$legacyPackageRoot = $configuredPublicRoot
    . DIRECTORY_SEPARATOR . 'packages'
    . DIRECTORY_SEPARATOR . 'block_builder';
$guard = DisposableEnvironmentGuard::fromEnvironment(expectedPackageRoot: $legacyPackageRoot);
$publicRoot = $guard->publicRoot;

defined('DIR_BASE') or define('DIR_BASE', $publicRoot);
$_SERVER['SCRIPT_FILENAME'] ??= $publicRoot . DIRECTORY_SEPARATOR . 'index.php';
$_SERVER['PHP_SELF'] ??= '/index.php';

require_once $publicRoot . DIRECTORY_SEPARATOR . 'concrete' . DIRECTORY_SEPARATOR . 'bootstrap' . DIRECTORY_SEPARATOR . 'configure.php';
require_once $publicRoot . DIRECTORY_SEPARATOR . 'concrete' . DIRECTORY_SEPARATOR . 'bootstrap' . DIRECTORY_SEPARATOR . 'autoload.php';

/** @var Concrete\Core\Application\Application $application */
$application = require $publicRoot . DIRECTORY_SEPARATOR . 'concrete' . DIRECTORY_SEPARATOR . 'bootstrap' . DIRECTORY_SEPARATOR . 'start.php';
$application->instance('app', $application);
$application->instance(Concrete\Core\Application\Application::class, $application);
$application->instance(Illuminate\Container\Container::class, $application);
$application->instance(ClassAutoloader::class, ClassAutoloader::getInstance());

$connection = $application->make(Connection::class);
$guard->assertActiveDatabase($connection);
$superUser = User::loginByUserID(USER_SUPER_ID);
if (!$superUser instanceof User || !$superUser->isSuperUser()) {
    throw new RuntimeException('The legacy fixture helper could not establish a disposable super-user session.');
}
$application->instance(User::class, $superUser);

$packageService = $application->make(PackageService::class);
$package = $packageService->getByHandle('block_builder');
if (!$package instanceof PackageEntity || !$package->isPackageInstalled() || $package->getPackageVersion() !== '2.8.1') {
    throw new RuntimeException('The legacy fixture helper requires installed Block Builder 2.8.1 sources.');
}
$packageController = $packageService->getClass('block_builder');
if (!$packageController instanceof \Concrete\Package\BlockBuilder\Controller) {
    throw new RuntimeException('The installed legacy Block Builder package controller could not be loaded.');
}
if (!class_exists(\BlockBuilder\Generator::class)) {
    throw new RuntimeException('The installed legacy Block Builder generator is unavailable.');
}

$blockPath = $guard->blocksRoot . DIRECTORY_SEPARATOR . LEGACY_FIXTURE_HANDLE;
if (file_exists($blockPath) || is_link($blockPath) || BlockType::getByHandle(LEGACY_FIXTURE_HANDLE) instanceof BlockTypeEntity) {
    throw new RuntimeException('The legacy upgrade fixture already exists; refusing to replace it.');
}

$fixturePath = $legacyPackageRoot
    . DIRECTORY_SEPARATOR . 'predefined_configs'
    . DIRECTORY_SEPARATOR . 'single_multiple_choice_field.json';
$fixtureContents = file_get_contents($fixturePath);
if ($fixtureContents === false) {
    throw new RuntimeException('The legacy single/multiple choice fixture could not be read.');
}
$fixtureData = json_decode($fixtureContents, true, 512, JSON_THROW_ON_ERROR);
if (!is_array($fixtureData) || array_is_list($fixtureData)) {
    throw new RuntimeException('The legacy single/multiple choice fixture is malformed.');
}
$fixtureData['blockName'] = 'Block Builder integration upgrade fixture';
$fixtureData['blockHandle'] = LEGACY_FIXTURE_HANDLE;
$fixtureData['blockDescription'] = 'Generated by Block Builder 2.8.1 before package upgrade.';
$fixtureData['installBlock'] = '1';
$fixtureData['excludedFromRemoval'] = ['templates'];

$generationResult = (new \BlockBuilder\Generator())->generateBlock($fixtureData);
if (
    !is_array($generationResult)
    || ($generationResult['blockInstalled'] ?? null) !== true
    || ($generationResult['blockRefreshed'] ?? null) !== false
) {
    throw new RuntimeException(sprintf(
        'Legacy fixture generation failed: %s',
        is_scalar($generationResult) ? (string) $generationResult : json_encode($generationResult),
    ));
}

$blockType = BlockType::getByHandle(LEGACY_FIXTURE_HANDLE);
if (!$blockType instanceof BlockTypeEntity) {
    throw new RuntimeException('The generated legacy fixture was not installed.');
}
$block = $blockType->add([
    'basic_single_choice_field_default_first' => 'show',
    'basic_single_choice_field_enhanced_first' => 'Show',
    'basic_single_choice_field_radio_list_first' => 'example',
    'basic_multiple_choice_field_default_first' => ['Show'],
    'basic_multiple_choice_field_enhanced_first' => ['2'],
    'basic_multiple_choice_field_checkbox_list_first' => ['some_data'],
    'entry' => [
        [
            'repeatable_single_choice_field_default_first' => 'aaa',
            'repeatable_single_choice_field_enhanced_first' => 'example2',
        ],
        [
            'repeatable_single_choice_field_default_first' => 'bbb',
            'repeatable_single_choice_field_enhanced_first' => 'some_data2',
        ],
    ],
]);
if (!$block instanceof Block || $block->getBlockID() < 1) {
    throw new RuntimeException('The legacy fixture block instance could not be created.');
}

$blockIdentifier = $block->getBlockID();
if ($connection->fetchOne(
    'SELECT basic_single_choice_field_default_first FROM ' . LEGACY_FIXTURE_MAIN_TABLE . ' WHERE bID = ?',
    [$blockIdentifier],
) !== 'show') {
    throw new RuntimeException('The legacy fixture main-table value was not persisted.');
}
$entryValues = $connection->fetchFirstColumn(
    'SELECT repeatable_single_choice_field_enhanced_first FROM ' . LEGACY_FIXTURE_ENTRIES_TABLE
    . ' WHERE bID = ? ORDER BY position, id',
    [$blockIdentifier],
);
if ($entryValues !== ['example2', 'some_data2']) {
    throw new RuntimeException('The legacy fixture repeatable values were not persisted in order.');
}

printf("Created legacy upgrade fixture block ID: %d\n", $blockIdentifier);
