<?php defined('C5_EXECUTE') or exit('Access Denied.');

/**
 * @var Concrete\Core\Form\Service\Form $form
 * @var BlockBuilder\Block\Dto\CreateBlockDto $config
 * @var array $fieldsWithError
 */
?>

<div class="mb-4 <?= h(in_array('registerViewAssetsCustomCode', $fieldsWithError) ? 'bb-has-error' : null); ?>">
    <?= $form->label('registerViewAssetsCustomCode', t('Custom code inside registerViewAssets() method')); ?>
    <?= $form->textarea('registerViewAssetsCustomCode', $config->registerViewAssetsCustomCode, ['style' => 'min-height: 200px;']); ?>
    <div class="form-text">
        <?= t('You can use this field to include js/css assets.'); ?>
        <br>
        <?= t('Be careful when inserting custom code, invalid syntax can lead to errors.'); ?>
        <br>
        <?= t('Use %s spaces as indentation.', 8); ?>
        <br>
        <strong class="d-block mt-2"><?= t('Example code'); ?>:</strong>
        <code class="bb-code-block">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// Load lightbox files
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->requireAsset('javascript',
            'feature/imagery/frontend');
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->requireAsset('css',
            'feature/imagery/frontend');
        </code>
    </div>
</div>

<div class="mb-4 <?= h(in_array('viewCustomCode', $fieldsWithError) ? 'bb-has-error' : null); ?>">
    <?= $form->label('viewCustomCode', t('Custom code inside view() method')); ?>
    <?= $form->textarea('viewCustomCode', $config->viewCustomCode, ['style' => 'min-height: 200px;']); ?>
    <div class="form-text">
        <?= t('You can use this field to include custom php code.'); ?>
        <br>
        <?= t('Be careful when inserting custom code, invalid syntax can lead to errors.'); ?>
        <br>
        <?= t('Use %s spaces as indentation.', 8); ?>
        <br>
        <strong class="d-block mt-2"><?= t('Example code'); ?>:</strong>
        <code class="bb-code-block">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$this->set('someVariable', 'value');
        </code>
    </div>
</div>

<div class="mb-4 <?= h(in_array('customControllerMethods', $fieldsWithError) ? 'bb-has-error' : null); ?>">
    <?= $form->label('customControllerMethods', t('Custom controller methods')); ?>
    <?= $form->textarea('customControllerMethods', $config->customControllerMethods, ['style' => 'min-height: 200px;']); ?>
    <div class="form-text">
        <?= t('You can use this field to put custom methods at the bottom of controller class.'); ?>
        <br>
        <?= t('Be careful when inserting custom code, invalid syntax can lead to errors.'); ?>
        <br>
        <?= t('Use %s spaces as indentation.', 4); ?>
        <br>
        <strong class="d-block mt-2"><?= t('Example code'); ?>:</strong>
        <code class="bb-code-block mt4">
            &nbsp;&nbsp;&nbsp;&nbsp;private function exampleMethod($exampleArgument)
            <br>&nbsp;&nbsp;&nbsp;&nbsp;{
            <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// Your custom code
            <br>&nbsp;&nbsp;&nbsp;&nbsp;}
        </code>
    </div>
</div>

<div class="mb-4 <?= h(in_array('excludedFromRemoval', $fieldsWithError) ? 'bb-has-error' : null); ?>">
    <?= $form->label('excludedFromRemoval', t('Excluded files and folders when rebuilding block')); ?>
    <?= $form->textarea('excludedFromRemoval', implode(PHP_EOL, $config->excludedFromRemoval), ['style' => 'min-height: 200px;']); ?>
    <div class="form-text">
        <?= t('You can use this field to exclude your own files/folders when rebuilding block (case scenario: you do not want to delete "templates" folder).'); ?>
        <br>
        <?= t('You can exclude first level files/folders only.'); ?>
        <br>
        <?= t('Do not exclude standard files/folders generated by Block Builder.'); ?>
        <br>
        <?= t('Every file/folder should be relative to controller.php (for example: templates) and put in new line.'); ?>
    </div>
</div>

