<?php

declare(strict_types=1);

namespace BlockBuilder\Block\Request;

final readonly class BlockFormFieldLabelProvider
{
    public function getLabel(string $fieldHandle): string
    {
        return match ($fieldHandle) {
            'blockName' => t('Block name'),
            'blockHandle' => t('Block handle'),
            'blockDescription' => t('Block description'),
            'blockWidth' => t('Block width'),
            'blockHeight' => t('Block height'),
            'blockTypeSet' => t('Block type set'),
            'blockIcon' => t('Block icon'),
            'cacheBlockRecord' => t('Cache block record'),
            'cacheBlockOutput' => t('Cache block output'),
            'cacheBlockOutputLifetime' => t('Cache block output lifetime'),
            'cacheBlockOutputOnPost' => t('Cache block output on post'),
            'cacheBlockOutputOnEditMode' => t('Cache block output in edit mode'),
            'cacheBlockOutputForRegisteredUsers' => t('Cache block output for registered users'),
            'supportSavingNullValues' => t('Support saving null values'),
            'ignorePageThemeGridFrameworkContainer' => t('Ignore page theme grid framework container'),
            'installBlock' => t('Install the block after creation'),
            'entriesAsFirstTab' => t('Entries as the first tab'),
            'maxNumberOfEntries' => t('Max. number of entries'),
            'highlightMultiElementFields' => t('Highlight multi-element fields'),
            'rebuildBlock' => t('Rebuild block'),
            'messageBasicTab' => t('Message displayed in the "Basic information" tab'),
            'messageEntriesTab' => t('Message displayed in the "Repeatable entries" tab'),
            'registerViewAssetsCustomCode' => t('Custom code inside registerViewAssets() method'),
            'viewCustomCode' => t('Custom code inside view() method'),
            'customControllerMethods' => t('Custom controller methods'),
            'excludedFromRemoval' => t('Excluded files and folders when rebuilding block'),
            'basicLabel' => t('Basic information'),
            'entriesLabel' => t('Entries'),
            'settingsLabel' => t('Settings'),
            'addAtTheTopLabel' => t('Add at the top'),
            'addAtTheBottomLabel' => t('Add at the bottom'),
            'copyLastEntryLabel' => t('Copy last entry'),
            'collapseAllLabel' => t('Collapse all'),
            'expandAllLabel' => t('Expand all'),
            'removeAllLabel' => t('Remove all'),
            'disableSmoothScrollLabel' => t('Disable smooth scroll'),
            'keepAddedEntryCollapsedLabel' => t('Keep added/copied entry collapsed'),
            'noEntriesFoundLabel' => t('No entries found.'),
            'maxNumberOfEntriesLabel' => t('Max. number of entries'),
            'removeEntryLabel' => t('Remove entry'),
            'duplicateEntryLabel' => t('Duplicate entry'),
            'duplicateEntryAndAddAtTheEndLabel' => t('Duplicate entry and add at the end'),
            'areYouSureLabel' => t('Are you sure?'),
            'requiredFieldsLabel' => t('Required fields'),
            'urlEndingLabel' => t('Custom string at the end of URL'),
            'urlEndingHelpTextLabel' => t('(e.g. #contact-form or ?ccm_paging_p=2)'),
            'textLabel' => t('Text'),
            'titleLabel' => t('Title'),
            'altTextLabel' => t('Alt text'),
            'linkFromSitemapLabel' => t('Link from Sitemap'),
            'linkFromFileManagerLabel' => t('Link from File Manager'),
            'externalLinkLabel' => t('External Link'),
            'showAdditionalFieldsLabel' => t('Show additional fields'),
            'hideAdditionalFieldsLabel' => t('Hide additional fields'),
            'newWindowLabel' => t('Open in new window'),
            'noFollowLabel' => t('Add nofollow attribute'),
            'yesLabel' => t('Yes'),
            'noLabel' => t('No'),
            'overrideThumbnailDimensionsLabel' => t('Override Thumbnail dimensions'),
            'overrideFullscreenImageDimensionsLabel' => t('Override Fullscreen Image dimensions'),
            'widthLabel' => t('Width'),
            'heightLabel' => t('Height'),
            'cropLabel' => t('Crop'),
            'pxLabel' => t('px'),
            'nothingSelectedLabel' => t('Nothing selected'),
            'noResultsMatchedLabel' => t('No results matched {0}'),
            'selectAllLabel' => t('Select All'),
            'deselectAllLabel' => t('Deselect All'),
            'fieldType' => t('Field type'),
            'label' => t('Label'),
            'handle' => t('Handle'),
            'required' => t('Required'),
            'helpText' => t('Help text'),
            'titleSource' => t('Use this field as title in repeatable entries'),
            'displayZeroValue' => t('Display zero ("0") in the view template'),
            'prefix' => t('Field prefix'),
            'suffix' => t('Field suffix'),
            'height' => t('Height'),
            'minHeight' => t('Minimum height'),
            'maxHeight' => t('Maximum height'),
            'minimumLength' => t('Minimum length'),
            'maximumLength' => t('Maximum length'),
            'datePattern' => t('PHP date pattern'),
            'minDate' => t('Minimum date'),
            'maxDate' => t('Maximum date'),
            'attachTimeSelector' => t('Attach time selector'),
            'minuteInterval' => t('Minute interval'),
            'expressHandle' => t('Express object handle'),
            'fileSetPrefix' => t('File Set prefix'),
            'showEndingField' => t('Show the "Custom string at the end of URL" field'),
            'showTextField' => t('Show the "Text" field'),
            'showTitleField' => t('Show the "Title" field'),
            'showNewWindowField' => t('Show the "Open in new window" field'),
            'showNoFollowField' => t('Show the "Add nofollow attribute" field'),
            'showAltTextField' => t('Show the "Alt text" field'),
            'createThumbnailImage' => t('Generate a thumbnail'),
            'thumbnailWidth' => t('Thumbnail width'),
            'thumbnailHeight' => t('Thumbnail height'),
            'thumbnailCrop' => t('Crop thumbnail'),
            'thumbnailEditable' => t('Editable thumbnail dimensions'),
            'createFullscreenImage' => t('Generate a fullscreen image'),
            'fullscreenWidth' => t('Fullscreen image width'),
            'fullscreenHeight' => t('Fullscreen image height'),
            'fullscreenCrop' => t('Crop fullscreen image'),
            'fullscreenEditable' => t('Editable fullscreen image dimensions'),
            'displayType' => t('Type'),
            'addEmptyOption' => t('Add an empty option'),
            'defaultValue' => t('Default value'),
            'placeholder' => t('Placeholder'),
            'listGenerationMethod' => t('List generation method'),
            'options' => t('Select options'),
            'customCode' => t('Custom code'),
            'size' => t('Size'),
            'step' => t('Step'),
            'minimum' => t('Minimum'),
            'maximum' => t('Maximum'),
            'displayedDecimals' => t('Displayed decimals'),
            'displayedDecimalSeparator' => t('Displayed decimal separator'),
            'displayedThousandsSeparator' => t('Displayed thousands separator'),
            'customConfig' => t('Custom editor configuration'),
            default => $fieldHandle,
        };
    }
}
