<?php

declare(strict_types=1);

namespace BlockBuilder\Block\Validation\Validator\Block;

use BlockBuilder\Block\Validation\AbstractValidator;
use BlockBuilder\Block\Validation\ValidationFeedback;
use BlockBuilder\Environment\EnvironmentService;
use BlockBuilder\NavigationTab\Enum\NavigationTabEnum;
use Symfony\Component\HttpFoundation\FileBag;

class ExcludedFromRemovalValidator extends AbstractValidator
{
    public function validate(array $data, ?FileBag $files = null): ValidationFeedback
    {
        $errors = [];

        if (!empty($data['excludedFromRemoval'])) {
            $forbiddenItems = [
                'css_files',
                FILENAME_BLOCK_ADD,
                FILENAME_BLOCK_EDIT,
                'auto.js',
                FILENAME_BLOCK_COMPOSER,
                EnvironmentService::CONFIG_BB_JS,
                FILENAME_BLOCK_CONTROLLER,
                FILENAME_BLOCK_DB,
                FILENAME_FORM,
                FILENAME_BLOCK_ICON,
                FILENAME_BLOCK_VIEW_SCRAPBOOK,
                FILENAME_BLOCK_VIEW,
            ];
            $items = explode(PHP_EOL, $data['excludedFromRemoval']);
            $isForbiddenItemFound = false;
            $forbiddenItem = null;
            foreach ($items as $item) {
                $item = trim($item);
                if (in_array($item, $forbiddenItems)) {
                    $isForbiddenItemFound = true;
                    $forbiddenItem = $item;
                    break;
                }
            }

            if ($isForbiddenItemFound) {
                $errors[] = t('Do not exclude files and folders generated by Block Builder (%s).', $forbiddenItem);
            }
        }

        if (!empty($errors)) {
            foreach ($errors as $error) {
                $this->addError(
                    error: $error,
                    field: 'excludedFromRemoval',
                    tab: NavigationTabEnum::CustomCode->getHandle(),
                );
            }
        }

        return $this->getValidationFeedback();
    }
}
