<?php

declare(strict_types=1);

namespace BlockBuilder\Block\Validation\Validator\Block;

use BlockBuilder\Block\Validation\AbstractValidator;
use BlockBuilder\Block\Validation\ValidationFeedback;

class ExcludedFromRemovalValidator extends AbstractValidator
{
    public function validate(array $data): ValidationFeedback
    {
        $errors = [];

        if (!empty($data['excludedFromRemoval'])) {
            $forbiddenItems = [
                'css_files',
                'add.php',
                'auto.js',
                'composer.php',
                'config-bb.json',
                'controller.php',
                'db.xml',
                'edit.php',
                'form.php',
                'icon.png',
                'scrapbook.php',
                'view.php',
            ];
            $items = explode(PHP_EOL, $data['excludedFromRemoval']);
            $isForbiddenItemFound = false;
            $forbiddenItem = null;
            foreach ($items as $item) {
                $item = trim($item);
                if (in_array($item, $forbiddenItems)) {
                    $isForbiddenItemFound = true;
                    $forbiddenItem = $item;
                    break;
                }
            }

            if ($isForbiddenItemFound) {
                $errors[] = t('Do not exclude files and folders generated by Block Builder (%s).', $forbiddenItem);
            }
        }

        if (!empty($errors)) {
            foreach ($errors as $error) {
                $this->addError(
                    error: $error,
                    field: 'excludedFromRemoval',
                    tab: 'custom-code',
                );
            }
        }

        return $this->getValidationFeedback();
    }
}
